name: docusaurus-scheduler
description: a docusarus action to schedule blog post releases
author: alvarolorentedev

# Define your inputs here.
inputs:
  base-folder:
    description: the folder for the drafts and unpublished articles
    required: true
    default: ./scheduler
  destination-folder:
    description: the folder for the publised articles
    required: true
    default: ./blog

runs:
  using: node20
  main: dist/index.js
